### ISSUE TITLE
BUG: `mv a b` leaves `a` in place

### ISSUE THREAD

**Issue by larsoner** [autofix-ci/action#10]
See [this PR in my project](https://github.com/mne-tools/mne-python/pull/12318) where I'm trying to implement a `git mv` on a file based on its name -- first I tried what is basically:
```
git mv other.rst 12318.other.rst
```
in my code followed by `autofix.ci/action`, but `other.rst` stuck around after the action. Then I tried plain `mv` and the same thing happened. See this Actions run where the `mv` is done:

https://github.com/mne-tools/mne-python/actions/runs/7292596505/job/19873926695#step:5:12

followed by the `autofix.ci` commit that only *adds* a file , does not delete the old one -- and should really `git mv` it:

https://github.com/mne-tools/mne-python/pull/12318/commits/c94ee0567b39db0e665e914755e3938830c2c1bc

**Comment by mhils** [comment]
Thanks for the clear repro! 🍰 
This is indeed a bug in the action Javascript. We're tripping on the fact that 
```shell
git diff --name-only --staged
```
only returns `12318.other.rst`, not `other.rst`.

**Comment by mhils** [comment]
This should be fixed now, thanks again!

**Comment by larsoner** [comment]
:astonished: that must be some sort of record response time... seems to [work](https://github.com/mne-tools/mne-python/pull/12318/commits/ab56ff38ee0d1ded80ec75c8e8e956f176d15a6a), thanks for the lightning-fast fix!
