### ISSUE TITLE
Any chance to sign autofix.ci up as a CircleCI user?

### ISSUE THREAD

**Issue by larsoner** [autofix-ci/action#11]
In our org we prevent unregistered users from spending our CircleCI credits. But it leads to this [block-unregistered-user](https://support.circleci.com/hc/en-us/articles/17441333580827-Why-do-I-see-a-block-unregistered-user-error-in-my-build-) any time `autofix.ci` pushes a commit to one of our PRs ([here](https://app.circleci.com/pipelines/github/mne-tools/mne-python/22451/workflows/010b3f0a-e1fc-4055-b627-ed95350d226c/jobs/62702) is an example).

Would it be possible to sign the autofix.ci bot/email up for CircleCI so that this stops happening? In theory it's free to sign up.

I could un-block unregistered users but that carries risks. And there is no way I know of to add unregistered users to an allowlist on CircleCI.

**Comment by mhils** [comment]
I'd be happy to do this, but the bot is a GitHub app, not a regular GitHub user account. I can't sign up for anything with it. Maybe this is something you can raise with CircleCI: How can bots such as dependabot/renovatebot/autofix.ci work with block-unregistered-user?

**Comment by larsoner** [comment]
Will do, writing that support request now :+1:
