### ISSUE TITLE
What does "replace with the latest commit hash" mean?

### ISSUE THREAD

**Issue by lizyChy0329** [autofix-ci/action#18]
What does "replace with the latest commit hash" mean? So, should I change the hash when the project updates every time?
```
- uses: autofix-ci/action@hash  # replace with the latest commit hash
```

I can see that Unocss use `- uses: autofix-ci/action@v1` also

**Comment by mhils** [comment]
Duplicate of https://github.com/autofix-ci/action/issues/17#issuecomment-2236548431?
