### ISSUE TITLE
Question: What's the difference between autofix.ci and an action that applies fixes and push directly to the branch?

### ISSUE THREAD

**Issue by so1ve** [autofix-ci/action#3]
What's the difference between autofix.ci and an action that applies fixes and push directly to the branch? I'm not quite understand why a server is needed.

**Comment by mhils** [comment]
autofix.ci can be used to fix pull requests from untrusted strangers on the internet, doing that with an action would be a security risk. If all your contributors are trusted colleagues, an action is perfectly fine!

**Comment by so1ve** [comment]
Ah, thanks for you reply! Love autofix.ci :)
