### ISSUE TITLE
feature request: comment on PR when automated commits are made

### ISSUE THREAD

**Issue by scarf005** [autofix-ci/action#7]
Hi, could the app add comments to PR as well using parameters such as `comment`?

## Rationale

> I feel this needs a warning somewhere in the PR template or the contributor docs. If the bot pushes a commit to the branch, and a contributor is fairly new to git, they may not know they'll need to pull the changes before pushing their own.

_Originally posted by @olanti-p in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3111#issuecomment-1703335826_

Automated commits may cause confusion for newcomers to Git, leading to merge conflicts. Adding comments with these commits could guide them on how to resolve this issue. I considered the approach in #6, but it requires `pull_request_target`, which goes against the core purpose of autofix-ci. I'd like to open a PR for this feature, but it seems the API server code is in a private repository.

**Comment by mhils** [comment]
Hi,

I implemented this at https://github.com/autofix-ci/action/tree/comments, see https://github.com/mhils/autofixer/pull/8 for an example. Does that match what you were looking for?

**Comment by scarf005** [comment]
yes, this is exactly what i've been looking for. it will help new contributors immensely. thank you!

**Comment by mhils** [comment]
Awesome, thanks! This is now live in v1.2 :)
