### ISSUE TITLE
Similar to pre-commit-ci/lite-action?

### ISSUE THREAD

**Issue by oprypin** [autofix-ci/action#8]
I see that the documentation mentions that "pre-commit.ci" can be used instead of "autofix.ci", though it has a somewhat different scope:
https://autofix.ci/setup#pre-commit

However something that may be harder to notice is that https://pre-commit.ci/lite.html **is** an exact equivalent of https://autofix.ci/.

That is, `uses: autofix-ci/action` and `uses: pre-commit-ci/lite-action` seem to be interchangeable as far as I can tell, though of course they each have a different associated GitHub App as well.

Both were created around the same time, too. Not sure if either project is aware of the other :sweat_smile: 
https://github.com/autofix-ci/action/commits/main
https://github.com/pre-commit-ci/lite-action/commits/main

**Comment by mhils** [comment]
We are, thanks! When I built autofix.ci, pre-commit lite didn't exist yet. Anthony started working on it shortly after, without being aware of autofix.ci. So yeah - _great minds think alike_ as English speakers would say; _two idiots, same thought_ as German speakers would say. 😄  Anthony and I chatted a while ago and are on good terms. :) Guess it's nice for users, either side has a backup option if one goes unmaintained.

If you're using pre-commit in some capacity, I'd encourage you to take your money to pre-commit.ci and not here. If not, I'm of course happy to welcome you as a autofix.ci user. :)
